lang: ru

# The priority of chat event interception by the plugin. I recommend using HIGH / HIGHEST.
# Available values:
# LOWEST | LOW | NORMAL | HIGH | HIGHEST | MONITOR
chat-event-priority: HIGHEST


#All messages with wrong or without chatSymbol will force to defaultChannel
defaultChannel: Local

#
#Chat elements that could be used in format line of channel.
#Chat elements take precedence over PlaceHolderAPI processing.
#There is {message} placeholder that will be processed by this plugin anyway.
#
#Click action variants: [SUGGEST_COMMAND, RUN_COMMAND, OPEN_URL]
#
ChatElements:
  player_name:
    text: "{player_name}"
    hover:
      - "player - {player_name}"
      - "balance - {vault_eco_balance}"
    click:
      type: SUGGEST_COMMAND
      value: "/msg {player_name}"

Channels:
  Local:
    speak-permission: cloudchat.channel.local
    message-sound: NONE
    cooldown: 0
    cooldown-bypass-permission: cloudchat.cooldown.bypass.local
    format: "&8[&7L&8] {player_name}&f: &7{message}"
    radius: 200
    quickSymbol: ''

  Global:
    speak-permission: cloudchat.channel.global
    message-sound: NONE
    cooldown: 3
    cooldown-bypass-permission: cloudchat.cooldown.bypass.global
    prefix: '&8[&2G&8]'
    format: "&8[&aG&8] {player_name}&f: &7{message}"
    radius: 0
    quickSymbol: '!'

  Trade:
    speak-permission: cloudchat.channel.trade
    message-sound: ENTITY_EXPERIENCE_ORB_PICKUP
    cooldown: 300
    cooldown-bypass-permission: cloudchat.cooldown.bypass.trade
    prefix: '&8[&a$&8]'
    format: "&8[&2T&8] {player_name}&f: &7{message}"
    radius: 0
    quickSymbol: '$'